//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("WNETWSModel", "FK_Transactions_CustomerID", "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WNETWorkshop.Customer), "Transactions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WNETWorkshop.Transaction), true)]
[assembly: EdmRelationshipAttribute("WNETWSModel", "FK_Transactions_FoodID", "FoodMenu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WNETWorkshop.FoodMenu), "Transactions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WNETWorkshop.Transaction), true)]

#endregion

namespace WNETWorkshop
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WNETWSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WNETWSEntities object using the connection string found in the 'WNETWSEntities' section of the application configuration file.
        /// </summary>
        public WNETWSEntities() : base("name=WNETWSEntities", "WNETWSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WNETWSEntities object.
        /// </summary>
        public WNETWSEntities(string connectionString) : base(connectionString, "WNETWSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WNETWSEntities object.
        /// </summary>
        public WNETWSEntities(EntityConnection connection) : base(connection, "WNETWSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FoodMenu> FoodMenus
        {
            get
            {
                if ((_FoodMenus == null))
                {
                    _FoodMenus = base.CreateObjectSet<FoodMenu>("FoodMenus");
                }
                return _FoodMenus;
            }
        }
        private ObjectSet<FoodMenu> _FoodMenus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Transaction> Transactions
        {
            get
            {
                if ((_Transactions == null))
                {
                    _Transactions = base.CreateObjectSet<Transaction>("Transactions");
                }
                return _Transactions;
            }
        }
        private ObjectSet<Transaction> _Transactions;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FoodMenus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoodMenus(FoodMenu foodMenu)
        {
            base.AddObject("FoodMenus", foodMenu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Transactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransactions(Transaction transaction)
        {
            base.AddObject("Transactions", transaction);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WNETWSModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        /// <param name="customerName">Initial value of the CustomerName property.</param>
        /// <param name="phoneNumber">Initial value of the PhoneNumber property.</param>
        public static Customer CreateCustomer(global::System.Int32 customerID, global::System.String customerName, global::System.Int32 phoneNumber)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            customer.CustomerName = customerName;
            customer.PhoneNumber = phoneNumber;
            return customer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value, "CustomerID");
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.Int32 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int32 value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, false, "CustomerName");
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, "PhoneNumber");
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.Int32 _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.Int32 value);
        partial void OnPhoneNumberChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WNETWSModel", "FK_Transactions_CustomerID", "Transactions")]
        public EntityCollection<Transaction> Transactions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaction>("WNETWSModel.FK_Transactions_CustomerID", "Transactions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaction>("WNETWSModel.FK_Transactions_CustomerID", "Transactions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WNETWSModel", Name="FoodMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FoodMenu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FoodMenu object.
        /// </summary>
        /// <param name="foodID">Initial value of the FoodID property.</param>
        /// <param name="foodName">Initial value of the FoodName property.</param>
        /// <param name="orderSize">Initial value of the OrderSize property.</param>
        public static FoodMenu CreateFoodMenu(global::System.Int32 foodID, global::System.String foodName, global::System.String orderSize)
        {
            FoodMenu foodMenu = new FoodMenu();
            foodMenu.FoodID = foodID;
            foodMenu.FoodName = foodName;
            foodMenu.OrderSize = orderSize;
            return foodMenu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FoodID
        {
            get
            {
                return _FoodID;
            }
            set
            {
                if (_FoodID != value)
                {
                    OnFoodIDChanging(value);
                    ReportPropertyChanging("FoodID");
                    _FoodID = StructuralObject.SetValidValue(value, "FoodID");
                    ReportPropertyChanged("FoodID");
                    OnFoodIDChanged();
                }
            }
        }
        private global::System.Int32 _FoodID;
        partial void OnFoodIDChanging(global::System.Int32 value);
        partial void OnFoodIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FoodName
        {
            get
            {
                return _FoodName;
            }
            set
            {
                OnFoodNameChanging(value);
                ReportPropertyChanging("FoodName");
                _FoodName = StructuralObject.SetValidValue(value, false, "FoodName");
                ReportPropertyChanged("FoodName");
                OnFoodNameChanged();
            }
        }
        private global::System.String _FoodName;
        partial void OnFoodNameChanging(global::System.String value);
        partial void OnFoodNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FoodOptions
        {
            get
            {
                return _FoodOptions;
            }
            set
            {
                OnFoodOptionsChanging(value);
                ReportPropertyChanging("FoodOptions");
                _FoodOptions = StructuralObject.SetValidValue(value, true, "FoodOptions");
                ReportPropertyChanged("FoodOptions");
                OnFoodOptionsChanged();
            }
        }
        private global::System.String _FoodOptions;
        partial void OnFoodOptionsChanging(global::System.String value);
        partial void OnFoodOptionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderSize
        {
            get
            {
                return _OrderSize;
            }
            set
            {
                OnOrderSizeChanging(value);
                ReportPropertyChanging("OrderSize");
                _OrderSize = StructuralObject.SetValidValue(value, false, "OrderSize");
                ReportPropertyChanged("OrderSize");
                OnOrderSizeChanged();
            }
        }
        private global::System.String _OrderSize;
        partial void OnOrderSizeChanging(global::System.String value);
        partial void OnOrderSizeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WNETWSModel", "FK_Transactions_FoodID", "Transactions")]
        public EntityCollection<Transaction> Transactions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaction>("WNETWSModel.FK_Transactions_FoodID", "Transactions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaction>("WNETWSModel.FK_Transactions_FoodID", "Transactions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WNETWSModel", Name="Transaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Transaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Transaction object.
        /// </summary>
        /// <param name="transactionID">Initial value of the TransactionID property.</param>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        /// <param name="foodID">Initial value of the FoodID property.</param>
        /// <param name="orderSize">Initial value of the OrderSize property.</param>
        /// <param name="orderDate">Initial value of the OrderDate property.</param>
        public static Transaction CreateTransaction(global::System.Int32 transactionID, global::System.Int32 customerID, global::System.Int32 foodID, global::System.String orderSize, global::System.DateTime orderDate)
        {
            Transaction transaction = new Transaction();
            transaction.TransactionID = transactionID;
            transaction.CustomerID = customerID;
            transaction.FoodID = foodID;
            transaction.OrderSize = orderSize;
            transaction.OrderDate = orderDate;
            return transaction;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransactionID
        {
            get
            {
                return _TransactionID;
            }
            set
            {
                if (_TransactionID != value)
                {
                    OnTransactionIDChanging(value);
                    ReportPropertyChanging("TransactionID");
                    _TransactionID = StructuralObject.SetValidValue(value, "TransactionID");
                    ReportPropertyChanged("TransactionID");
                    OnTransactionIDChanged();
                }
            }
        }
        private global::System.Int32 _TransactionID;
        partial void OnTransactionIDChanging(global::System.Int32 value);
        partial void OnTransactionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                OnCustomerIDChanging(value);
                ReportPropertyChanging("CustomerID");
                _CustomerID = StructuralObject.SetValidValue(value, "CustomerID");
                ReportPropertyChanged("CustomerID");
                OnCustomerIDChanged();
            }
        }
        private global::System.Int32 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int32 value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FoodID
        {
            get
            {
                return _FoodID;
            }
            set
            {
                OnFoodIDChanging(value);
                ReportPropertyChanging("FoodID");
                _FoodID = StructuralObject.SetValidValue(value, "FoodID");
                ReportPropertyChanged("FoodID");
                OnFoodIDChanged();
            }
        }
        private global::System.Int32 _FoodID;
        partial void OnFoodIDChanging(global::System.Int32 value);
        partial void OnFoodIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderOptions
        {
            get
            {
                return _OrderOptions;
            }
            set
            {
                OnOrderOptionsChanging(value);
                ReportPropertyChanging("OrderOptions");
                _OrderOptions = StructuralObject.SetValidValue(value, true, "OrderOptions");
                ReportPropertyChanged("OrderOptions");
                OnOrderOptionsChanged();
            }
        }
        private global::System.String _OrderOptions;
        partial void OnOrderOptionsChanging(global::System.String value);
        partial void OnOrderOptionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderSize
        {
            get
            {
                return _OrderSize;
            }
            set
            {
                OnOrderSizeChanging(value);
                ReportPropertyChanging("OrderSize");
                _OrderSize = StructuralObject.SetValidValue(value, false, "OrderSize");
                ReportPropertyChanged("OrderSize");
                OnOrderSizeChanged();
            }
        }
        private global::System.String _OrderSize;
        partial void OnOrderSizeChanging(global::System.String value);
        partial void OnOrderSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value, "OrderDate");
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private global::System.DateTime _OrderDate;
        partial void OnOrderDateChanging(global::System.DateTime value);
        partial void OnOrderDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WNETWSModel", "FK_Transactions_CustomerID", "Customers")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("WNETWSModel.FK_Transactions_CustomerID", "Customers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("WNETWSModel.FK_Transactions_CustomerID", "Customers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("WNETWSModel.FK_Transactions_CustomerID", "Customers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("WNETWSModel.FK_Transactions_CustomerID", "Customers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WNETWSModel", "FK_Transactions_FoodID", "FoodMenu")]
        public FoodMenu FoodMenu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FoodMenu>("WNETWSModel.FK_Transactions_FoodID", "FoodMenu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FoodMenu>("WNETWSModel.FK_Transactions_FoodID", "FoodMenu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FoodMenu> FoodMenuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FoodMenu>("WNETWSModel.FK_Transactions_FoodID", "FoodMenu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FoodMenu>("WNETWSModel.FK_Transactions_FoodID", "FoodMenu", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
