<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Main.Master" CodeBehind="BookCRUD.aspx.cs" Inherits="WNETCA_SA46G9.Owner.BookCRUD" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div>
        <asp:Label ID="Label1" runat="server" Height="28px" Text="Select Book Cover Image to Upload"></asp:Label>
        <asp:FileUpload ID="FileUpload1" runat="server" Width="424px" AllowMultiple="true" />
        <asp:Button ID="Button1" runat="server" Height="28px" OnClick="Button1_Click" Text="Submit" />
    </div>
    <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/Owner/DiscountCRUD.aspx">Maintain Discounts</asp:HyperLink>
    
        <div style="height: 600px">
            <asp:Gridview id="GridView1" runat="server" allowpaging="True" allowsorting="True" datasourceid="entitydatasource2" horizontalalign="Left" pagesize="20" emptydatatext="no item exists" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="BookID">   

                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="BookID" HeaderText="BookID" InsertVisible="False" ReadOnly="True" SortExpression="BookID" />
                    <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                    <asp:BoundField DataField="CategoryID" HeaderText="CategoryID" SortExpression="CategoryID" />
                    <asp:BoundField DataField="ISBN" HeaderText="ISBN" SortExpression="ISBN" />
                    <asp:BoundField DataField="Author" HeaderText="Author" SortExpression="Author" />
                    <asp:BoundField DataField="Stock" HeaderText="Stock" SortExpression="Stock" />
                    <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />                    
                    <asp:BoundField DataField="BookDiscount" HeaderText="Book Discount" SortExpression="BookDiscount" />
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:Gridview>
            <asp:SqlDataSource id="entitydatasource2" runat="server" connectionstring="<%$ ConnectionStrings:myDB %>" SelectCommand="SELECT * FROM [Books]">
        </asp:SqlDataSource>
                </div>
    </asp:Content>
